#!/usr/bin/env bash
dir=$(dirname $0)
ln -s ${dirname}/../bin/disperse /usr/local/bin/disperse
ln -s ${dirname}/spore /usr/local/bin/spore
ln -s ${dirname}/spore-download-and-apply /usr/local/bin/spore-download-and-apply 
